coreruleset/crs-toolchain

regex/operators/assembler.go
regex/operators/assembler_test.go
regex/processors/assemble.go
regex/processors/assemble_test.go
regex/processors/cmdline.go
regex/processors/cmdline_test.go
regex/processors/context.go
regex/processors/processors.go

The main goal of this PR was to clean up the regular expressions generated by the Go regexp library and replace things like `(?-s:.)` with `.`.
While doing this, I discovered that the test suite I was adding tests to for these cases wasn't being run and enabling it showed many of them were failing. I've fixed all of the tests and the associated code, where necessary.

Dont use flags for meta chars

---

.golangci.yml
cmd/regex.go
cmd/regex_compare.go
cmd/regex_format.go
cmd/regex_format_test.go
cmd/regex_update.go
cmd/regex_update_test.go
cmd/root.go
cmd/root_test.go
logger/logger.go
magefile.go
main.go
regex/operators/assembler.go
regex/parser/parser.go
regex/parser/parser_test.go
regex/processors/assemble.go
regex/processors/cmdline.go

I wanted to fix one thing in the formatter and added up with this huge PR. Unfortunately, most of the things tie into each other.
- format all directives consistently
- also indent comments
- don't indent processors without body
- fix broken tests (all packages)
- let parser know that it must retain lines for formatting
- don't run include or definition processors when formatting
- fix order of logger instantiation

Fix formatter (and various issues)

---

cmd/flag_types.go
cmd/regex_compare_test.go
cmd/regex_format_test.go
cmd/regex_generate_test.go
cmd/regex_test.go
cmd/regex_update_test.go
cmd/root_test.go
cmd/util_renumber_tests_test.go
context/context.go
regex/parser/parser_test.go
regex/processors/assemble_test.go

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>
After merging https://github.com/coreruleset/coreruleset/pull/3002 we need to update all data paths here also.

fix(dir): update data directory after movement

---

regex/definitions.go
regex/parser/parser.go
regex/parser/parser_test.go

Warn if after doing definitions substitution there are still references to names without resolution.
They might happen because something was moved or renamed, or there is a typo somewhere.
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>
Fixes #39.

feat: add check for unknown definitions

---

regex/definitions.go
regex/operators/assembler_test.go
regex/parser/parser.go
regex/parser/parser_test.go

In the toolchain, the parser holds the flags, prefixes and suffixes and the assembler uses them when finalizing the assembly. The parsers of include files, however, aren't known to the assembler. In addition, the flags, prefixes, and suffixes in include files must be scoped to the include file.
This commit adds a new function to post process include file parsing. The included content is enclosed in a new assemble block and flags, prefixes, and suffixes are perpended / appended to the content.
Fixes #40.

fix(parser): handle flags, prefixes, and suffixes in include files

---

cmd/flag_types.go
cmd/regex.go
cmd/regex_compare.go
cmd/regex_compare_test.go
cmd/regex_format.go
cmd/regex_format_test.go
cmd/regex_generate.go
cmd/regex_generate_test.go
cmd/regex_test.go
cmd/regex_update.go
cmd/regex_update_test.go
cmd/root_test.go
cmd/util_renumber_tests_test.go
context/context.go
regex/definitions.go
regex/parser/parser.go
regex/parser/parser_test.go
regex/processors/assemble_test.go

- regexp-assembly files extension was renamed to `.ra`.
- `data` directory was renamed as `regexp-assembly`
Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>

Update directory and extensions

---

cmd/regex_compare.go
cmd/regex_update.go
regex/definitions.go

I've tried to add a test to verify that compare works as it should but I failed to make zerolog use a different output. It seems impossible to change the root logger, it can only be duplicated (I even tried to use hooks). We'll need to fix that some other time.

fix: fix regex for finding regex in rules

---

regex/operators/assembler_test.go
regex/processors/assemble.go

When mixing output of stored expressions and alternations, alternations will no longer be appended at the end but at the correct position, i.e., before the append directive.

fix: correct output order of assemble processor

---

cmd/regex_format.go
cmd/regex_format_test.go
cmd/util_renumber_tests.go
cmd/util_renumber_tests_test.go
regex/definitions.go
util/renumber_tests.go
util/renumber_tests_test.go

- don't remove trailing newline character
- skip other files in the test directories
- add github output
- add check flag to support linting on GitHub
- use same arguments and flags as for all other commands, for consistency

fix: improve test renumbering

---

regex/operators/assembler_test.go
regex/processors/cmdline.go
regex/processors/cmdline_test.go

Additional detection of:
- hiding empty variables by using logical operators, e.g. `nc&&$b -nlvp 777`
- brace expansion in shells to omit detection of white space separation, e.g., `{n\c,-nlvp,777}`. Note that expansion would require a leading empty string to work, e.g. `""{n\c,-nlvp,777}`, which will be expanded to `nc -nlvp 777`
Improved comments explaining the supported detections

Improve Unix shell evasion detection

---

regex/parser/parser.go
regex/parser/parser_test.go

Do not add superfluous empty lines with output comments. These lines will not run through a parser a second time and thus remain in the output. In the end, those empty lines will produce empty matches `(?:)`.

fix: properly prefix / suffix includes

---

regex/definitions.go
util/renumber_tests.go

The regular expression used to match test titles did not match empty test titles.

fix: better matching of test title

---

.gitignore
cmd/root.go
main.go

Signed-off-by: Felipe Zipitria <felipe.zipitria@owasp.org>
Embeds version information at build time.
Example:
```
❯ goreleaser build --clean
• starting build...
• loading config file                              file=.goreleaser.yml
• loading environment variables
• getting and validating git state
• building...                                    commit=b3179cfa53e761a36b988cb5fd4b9978e6fc9c06 latest tag=v1.3.9
• parsing tag
• setting defaults
• running before hooks
• running                                        hook=go mod download
• checking distribution directory
• cleaning dist
• loading go mod information
• build prerequisites
• writing effective config file
• writing                                        config=dist/config.yaml
• building binaries
• building …
```

feat: adds build version into executable

---

cmd/regex_format.go
cmd/regex_format_test.go

The `format` command did not add the assembly file header when it was missing due to an inverted conditional.

fix: format command adds the assembly file header

---

regex/parser/include_except_builder.go
regex/parser/include_except_test.go
regex/parser/include_test.go

The logic for parsing suffix replacements did not allow for the empty string. This commit remedies that by using `""` as a special literal to mean the empty string.

feat: enable empty string as suffix replacement

---

magefile.go

- update lint to support go 1.21

chore: update golangci-lint version

---

.github/workflows/lint.yml
.github/workflows/regression.yml
.github/workflows/release.yml
go.mod
regex/operators/assembler.go
regex/operators/assembler_test.go
regex/processors/assemble_test.go

Go 1.22 includes improved printing of regular expression flags.
See https://github.com/golang/go/issues/57950
See https://go-review.googlesource.com/c/go/+/507015

feat: update to Go 1.22

---

chore/update_copyright.go
chore/update_copyright_test.go
magefile.go
regex/definitions.go

- the `ver:` part of SecRules was not being updated
- update also the `SecComponentSignature`
- check that we add a last newline at EOF, if the file didn't had it
Fixes #114.

fix: update copyright year in SecRule ver and SecComponentSignature

---

cmd/regex_format.go
cmd/regex_format_test.go
regex/definitions.go
regex/parser/parser.go

Fixes #118 and #119.
- updated comment regex to match [comments that start with space](https://github.com/coreruleset/coreruleset/blob/6f8675f17f31ebebff664bbee84578f8d0a65703/regex-assembly/941210.ra#L220).
- do not match on character classes, unless we have an odd number of escapes (e.g. `\S` vs. `\\S`, the former is a char class, the latter is an escaped quote followed by uppercase `S`).
- parses definitions for uppercase also.
- added tests for everything.

fix: position indicator at start of line

---

go.mod
go.sum
regex/operators/assembler.go
regex/operators/assembler_test.go
regex/operators/operators.go
renovate.json

This change fixes the issue uncovered with the upgrade to rassemble-go v0.1.1.
- consider alternations when removing flag groups
- handle top level group specially

fix: improve group removal step

---

regex/operators/assembler.go
regex/processors/cmdline.go
regex/processors/cmdline_test.go
regex/utils.go
regex/utils_test.go

Until now, `~` and `@` would be replaced by the evasion suffix regardless of their position in the string, even though the evasion suffix was only ever intended to be used as a suffix. With this commit, `~` and `@` are only treated specially if they occur as the last character on the line.
In addition, it is now possible to escape a terminal `~` or `@` with a backslash. The only limitation is that the toolchain cannot handle a sequence such as `abc\\~`, which would result in `abc\\<suffix>` instead of `abc\<suffix>` because there's no special handling of backslash espaces in general.
Fixes #185

fix: restrict use of evasion modifiers to end of line

---

cmd/regex_format.go
cmd/regex_format_test.go
regex/operators/assembler.go
utils/utils.go
utils/utils_test.go

Check only character classes for uppercase letters in case-insensitive expressions. Other casing in assembly files can give context and it may be better to leave it as is.

feat: fail format validation on unnecessary uppercase character classes

---

regex/operators/assembler.go
regex/operators/assembler_test.go

Reference Issue: https://github.com/coreruleset/crs-toolchain/issues/221

fix: incorrect hex representation of Unicode characters (Example: \x2019 instead of \x{2019})

---

util/fp_finder.go
util/fp_finder_test.go

Seems like I refactored too much with initial PR #219 and inadvertently removed the sorting 😊
This commit will fix it.

fix: sort entries before printing for fp-finder command
